export const ERRORS = [
    {msg:"Sai thông tin đăng nhập", err:101},
    {msg:"Tài khoản đã bị khóa", err:102},
    {msg:"Không tìm thấy kho thuộc quyền quản lý của tài khoản.", err:103},
    {msg:"Tên tài khoản không được trống.", err:104},
    {msg:"Tên tài khoản bị trùng.", err:105},
    {msg:"Email đã được sử dụng.", err:106},
    {msg:"Tên tài khoản không được trống.",err:107},
    {msg:"Họ tên không được trống",err:108},
    {msg:"File không hợp lệ.", err:109},
    {msg:"Tên cửa hàng không được trống.", err:110},
    {msg:"Người cập nhật không thích hợp.", err:111},
    {msg:"Thêm cửa hàng thất bại", err:112},
    {msg:"Cập nhật cửa hàng thất bại", err:113},
    {msg:"Tên kho không được trống.", err:114},
    {msg:"Thêm kho thất bại", err:115},
    {msg:"Cập nhật kho thất bại", err:116},
    {msg:"Họ và tên không được trống.", err:117},
    {msg:"Cần chọn một kho.", err:118},
    {msg:"Cần ít nhất một hàng hóa trong phiếu nhập.", err:119},
    {msg:"Cần chọn một cửa hàng.", err:120},
    {msg:"Cần ít nhất một hàng hóa trong phiếu xuất.", err:121},
    {msg:"Tên vị trí lưu trữ không được trống.", err:122},
    {msg:"Thêm vị trí lưu trữ thất bại", err:123},
    {msg:"Cập nhật vị trí lưu trữ thất bại", err:124},
    {msg:"Tên hàng hóa không được trống.", err:125},
    {msg:"Trạng thái hàng hóa không được trống.", err:126},
    {msg:"Thêm hàng hóa thất bại", err:127},
    {msg:"Cập nhật hàng hóa thất bại", err:128}


];

export const MSG = {
    0:"Đăng nhập thành công.",
    1:"Có lỗi xảy ra.",
    2:"Có lỗi xảy ra khi tạo tài khoản. ",
    3:"Tạo tài khoản thành công.",
    4:"Cập nhật thành công.",
    5:"Cập nhật thất bại.",
    6:"Thêm cửa hàng thành công",
    7:"Thêm kho thành công",
    8:"Thêm vị trí lưu trữ thành công",
    9:"Cập nhật vị trí lưu trữ thành công",
    10:"Thêm hàng hóa thành công",
    11:"Cập nhật hàng hóa thành công",
}